import Head from 'next/head'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Google v3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <h1>Hello World</h1>
      
    </div>
  )
}
//  git config --global user.email "you@example.com"
//   git config --global user.name "Your Name"
